export enum InvitationErrorType {
    INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
    EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
    EVENT_FULL = 'EVENT_FULL',
    EVENT_FULL_QUICK_REGISTRATION = 'EVENT_FULL_QUICK_REGISTRATION',
    UNAUTHORIZED = 'UNAUTHORIZED',
    UNAUTHORIZED_QUICK_REGISTRATION = 'UNAUTHORIZED_QUICK_REGISTRATION',
    FORBIDDEN = 'FORBIDDEN'
}