export enum InvitationErrorType {
    NOT_FOUND = 'NOT_FOUND',
    EVENT_FULL = 'EVENT_FULL',
    EVENT_FULL_QUICK_REGISTRATION = 'EVENT_FULL_QUICK_REGISTRATION',
    UNAUTHORIZED = 'UNAUTHORIZED',
    UNAUTHORIZED_QUICK_REGISTRATION = 'UNAUTHORIZED_QUICK_REGISTRATION',
    FORBIDDEN = 'FORBIDDEN'
}